include: 'https://raw.githubusercontent.com/Nitrokey/common-ci-jobs/master/common_jobs.yml'

stages:
  - pull-github
  - build 
  - deploy

variables:
  GIT_STRATEGY: clone            
  GIT_DEPTH: 0                    
  GIT_SUBMODULE_STRATEGY: recursive 
  SCRIPTS_REPO: git@git.dotplex.com:nitrokey/gitlab-ci.git
  REPO_USER: nitrokey
  REPO_NAME: ubuntu-oem
  MAIN_BRANCH: nitropc
  COMMON_PULL: "true"
  COMMON_UPLOAD_NIGHTLY: "false"
  COMMON_GITHUB_RELEASE: "false"
  COMMON_UPLOAD_FILES: "true"
  DEVICE_FOLDER: "nitropc"
  UPLOAD_FOLDER: "ubuntu-oem"

oem-build:
  image: registry.git.dotplex.com/nitrokey/gitlab-ci/ci-oem-release@sha256:7cf04f607158a6e2bc7db210c36edb87071f91e0df119c29f02df2112eb44ad1
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  tags:
    - docker
  stage: build
  script:
    - ./make-image.sh
    - ls
    - mkdir -p artifacts
    - cp *nitropc*.iso artifacts/
  after_script:
    - wget $icon_server/checkmark/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHA/$CI_JOB_NAME/$CI_JOB_STATUS/${CI_JOB_URL#*/*/*/}
  artifacts:
    paths:
      - artifacts
    expire_in: 1 hrs